name: list_boilerplate
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  logging: ^1.0.1
  logging_appenders: ^1.0.0
  catcher: ^0.6.8
  intl: ^0.17.0
  intl_utils: ^2.4.0
  google_fonts: ^2.1.0
  flutter_platform_widgets: ^1.9.5
  responsive_framework: ^0.1.4
  async: ^2.7.0
  equatable: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^4.1.0
  golden_toolkit: ^0.10.0
  build_runner: ^2.0.5
  mocktail: ^0.1.4
  mockingjay: ^0.1.0
  given_when_then: ^0.2.0


  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    # required for eBay Golden Toolkit library
    - images/
    # required for eBay Golden Toolkit library for Goldens 
    - google_fonts/
flutter_intl:
  enabled: true   
  class_name: S   
  main_locale: en 
  arb_dir: lib/src/localization
  output_dir: lib/src/localization_gen
  use_deferred_loading: false

